"""empty message

Revision ID: 730627b2d007
Revises: 
Create Date: 2022-10-28 11:51:24.771107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730627b2d007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('promedio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('apellido', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('horas', sa.Integer(), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('preofesor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preofesor'], ['profesor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materia')
    op.drop_table('profesor')
    op.drop_table('estudiante')
    # ### end Alembic commands ###
