# Generated by Django 4.1.2 on 2022-10-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('semestre', models.CharField(max_length=255)),
                ('creditos_teoricos', models.IntegerField()),
                ('creditos_practicos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.CharField(max_length=255)),
                ('numero_seguro', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('materias', models.ManyToManyField(to='universidad.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('semestre', models.CharField(max_length=255)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='universidad.tutor')),
            ],
        ),
    ]
